/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.70
 * Generated at: 2024-05-30 23:41:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1717107116065L));
    _jspx_dependants.put("jar:file:/C:/Users/Alumno/.ssh/Proyecto/sfrentas/build/web/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153406682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write(" \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("   <head>\r\n");
      out.write("      <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\r\n");
      out.write("      <link rel=\"icon\" type=\"image/x-icon\" href=\"AcosoZer0Batiz/Imagenes/favicon.ico\">\r\n");
      out.write("      <link href=\"css/IndexDesigns.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("      <link href=\"css/OverallDesigns.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("      <link href=\"https://fonts.googleapis.com/icon?family=Material+Icons&quot; rel=\"stylesheet\">\r\n");
      out.write("      <link href=\"css/Buscar_Reportes.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("  <script src=\"https://code.jquery.com/jquery-2.2.4.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("      <title> AcosoZer0Batiz </title>\r\n");
      out.write("   </head>\r\n");
      out.write("   <body>\r\n");
      out.write("\r\n");
      out.write("       <a class=\"navbar-brand\" href=\"AcosoZer0Batiz/index.html\">\r\n");
      out.write("          <img src=\"AcosoZer0Batiz/Imagenes/logo.png\" alt=\"AcosoZer0Batiz\">\r\n");
      out.write("      </a>\r\n");
      out.write("      <div class=\"dropdown-container\">\r\n");
      out.write("         <ul class=\"navbars-nav btn-group my-2 my-lg-0\" role=\"group\">\r\n");
      out.write("            <a\r\n");
      out.write("               style=\"color: white; cursor: pointer\"\r\n");
      out.write("               class=\"dropdown-toggle\"\r\n");
      out.write("               data-toggle=\"dropdown\">\r\n");
      out.write("            <i class=\"fas fa-user-tie\"></i> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${logueo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("            </a>\r\n");
      out.write("            <div class=\"dropdown-menu text-center dropdown-menu-right\">\r\n");
      out.write("               <a class=\"dropdown-item\" href=\"#\"\r\n");
      out.write("                  ><img src=\"img/usuario.png\" alt=\"60\" height=\"60\"\r\n");
      out.write("                  /></a>\r\n");
      out.write("               <a class=\"dropdown-item\" href=\"#\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</a>\r\n");
      out.write("               <a\r\n");
      out.write("                  class=\"dropdown-item\"\r\n");
      out.write("                  href=\"#\"\r\n");
      out.write("                  data-toggle=\"modal\"\r\n");
      out.write("                  data-target=\"#myModal\"\r\n");
      out.write("                  >");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${correo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</a\r\n");
      out.write("                  >\r\n");
      out.write("               <div class=\"dropdown-divider\"></div>\r\n");
      out.write("               <a\r\n");
      out.write("                  class=\"dropdown-item\"\r\n");
      out.write("                  href=\"Controlador?accion=MisCompras\"\r\n");
      out.write("                  >Mis Compras</a\r\n");
      out.write("                  >\r\n");
      out.write("               <div class=\"dropdown-divider\"></div>\r\n");
      out.write("               <a\r\n");
      out.write("                  class=\"dropdown-item\"\r\n");
      out.write("                  href=\"./Controlador?accion=Salir\">\r\n");
      out.write("               <i class=\"fas fa-arrow-right\"> Salir</i></a\r\n");
      out.write("                  >\r\n");
      out.write("            </div>\r\n");
      out.write("         </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("      <nav class=\"navbar navbar-expand-lg navbar-dark bg-dark\">\r\n");
      out.write("      \r\n");
      out.write("         <div class=\"collapse navbar-collapse\" id=\"navbarTogglerDemo03\">\r\n");
      out.write("            <ul class=\"navbar-nav mr-auto mt-2 mt-lg-0\">\r\n");
      out.write("               <li class=\"nav-item active\">\r\n");
      out.write("                   <a class=\"nav-link\" href=\"INFORMATIVO/index.html\">\r\n");
      out.write("                     <div class=\"menu_index\">\r\n");
      out.write("                        <img src=\"https://i.redd.it/wixrspq3mhc51.jpg\" />\r\n");
      out.write("                        <img class=\"top rar\" src=\"img/info1.png\" />\r\n");
      out.write("                     </div> \r\n");
      out.write("                  </a> <div class=\"texto\" style=\"font-family: 'Pacifico', cursive; font-size: 48px; font-weight: bold; color: #ffffff; text-align: center;\">\r\n");
      out.write("    Informate\r\n");
      out.write("  </div>\r\n");
      out.write("               </li>\r\n");
      out.write("               <li class=\"nav-item active\">\r\n");
      out.write("                   <a class=\"nav-link\" href=\"AcosoZer0Batiz/index.html\">\r\n");
      out.write("                     <i class=\"fas fa-cart-plus\">\r\n");
      out.write("                     </i>\r\n");
      out.write("                     <div class=\"menu_index\">\r\n");
      out.write("                        <img src=\"img/empresa2.png\" />\r\n");
      out.write("                        <img class=\"top rar\" src=\"img/empresa1.png\"/>\r\n");
      out.write("                     </div>\r\n");
      out.write("                  </a><div class=\"texto\" style=\"font-family: 'Pacifico', cursive; font-size: 48px; font-weight: bold; color: #ffffff; text-align: center;\">\r\n");
      out.write("    Empresa\r\n");
      out.write("  </div>\r\n");
      out.write("               </li>\r\n");
      out.write("               <li class=\"nav-item active\">\r\n");
      out.write("                  <a class=\"nav-link\" href=\"./ReporteServlet?action=list\">\r\n");
      out.write("                     <div class=\"menu_index\">\r\n");
      out.write("                        <img src=\"img/reporte2.png\" />\r\n");
      out.write("                        <img class=\"top rar\" src=\"https://i.pinimg.com/736x/e8/6c/c6/e86cc64fd3aee67168ba578921c55dc9.jpg\" />\r\n");
      out.write("                     </div>\r\n");
      out.write("                  </a><div class=\"texto\" style=\"font-family: 'Pacifico', cursive; font-size: 48px; font-weight: bold; color: #ffffff; text-align: center;\">\r\n");
      out.write("    Informe\r\n");
      out.write("  </div>\r\n");
      out.write("               </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("         </div>\r\n");
      out.write("      </nav>\r\n");
      out.write("      <div class=\"container1 mt-5\">\r\n");
      out.write("         <div class=\"row\">\r\n");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Div para mostrar los resultados de la búsqueda -->\r\n");
      out.write("<div id=\"productResults\"></div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    function toggleSearchFields() {\r\n");
      out.write("        var searchOption = document.getElementById('searchOption').value;\r\n");
      out.write("        var searchInput = document.getElementById('searchInput');\r\n");
      out.write("        var searchDate = document.getElementById('searchDate');\r\n");
      out.write("        \r\n");
      out.write("        if (searchOption === 'date') {\r\n");
      out.write("            searchInput.style.display = 'none';\r\n");
      out.write("            searchDate.style.display = 'inline-block';\r\n");
      out.write("        } else {\r\n");
      out.write("            searchInput.style.display = 'inline-block';\r\n");
      out.write("            searchDate.style.display = 'none';\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function searchProducts() {\r\n");
      out.write("        // Obtener el texto ingresado en el campo de búsqueda\r\n");
      out.write("        var searchText = document.getElementById('searchInput').value.toLowerCase();\r\n");
      out.write("        var searchDate = document.getElementById('searchDate').value;\r\n");
      out.write("        // Obtener la opción de búsqueda seleccionada\r\n");
      out.write("        var searchOption = document.getElementById('searchOption').value;\r\n");
      out.write("        \r\n");
      out.write("        // Obtener todos los elementos de producto\r\n");
      out.write("        var products = document.querySelectorAll('[data-product-name], [data-product-description], [data-product-date]');\r\n");
      out.write("        \r\n");
      out.write("        // Iterar sobre cada producto y mostrar u ocultar según la búsqueda\r\n");
      out.write("        products.forEach(function(product) {\r\n");
      out.write("            var name = product.getAttribute('data-product-name').toLowerCase();\r\n");
      out.write("            var description = product.getAttribute('data-product-description').toLowerCase();\r\n");
      out.write("            var date = product.getAttribute('data-product-date');\r\n");
      out.write("            \r\n");
      out.write("            if ((searchOption === 'name' && name.includes(searchText)) || \r\n");
      out.write("                (searchOption === 'description' && description.includes(searchText)) || \r\n");
      out.write("                (searchOption === 'date' && date === searchDate)) {\r\n");
      out.write("                product.style.display = 'block'; // Mostrar el producto si coincide con la opción de búsqueda\r\n");
      out.write("            } else {\r\n");
      out.write("                product.style.display = 'none'; // Ocultar el producto si no coincide\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    // Inicializar el estado de los campos de búsqueda\r\n");
      out.write("    toggleSearchFields();\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- Modal Iniciar Session o Registrarse -->\r\n");
      out.write("      <div class=\"modal fade\" id=\"myModal\" tabindex=\"-1\" role=\"dialog\">\r\n");
      out.write("          \r\n");
      out.write("         <div class=\"modal-dialog modal-dialog-centered\" role=\"document\">\r\n");
      out.write("            <div class=\"container col-lg-9\">\r\n");
      out.write("               <div class=\"modal-content\">\r\n");
      out.write("                   <div class=\"modalimage\">\r\n");
      out.write("                         <div class=\"recuadro\">\r\n");
      out.write("                         <img id=\"modalimage\" src=\"\" class=\"rounded-image\"> </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"pr-2 pt-1\">\r\n");
      out.write("                     <button\r\n");
      out.write("                        type=\"button\"\r\n");
      out.write("                        class=\"close\"\r\n");
      out.write("                        data-dismiss=\"modal\">\r\n");
      out.write("                     <span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("                     </button>\r\n");
      out.write("          </div>\r\n");
      out.write("                      \r\n");
      out.write("                  <div class=\"text-center\">\r\n");
      out.write("                     <img src=\"img/usuario.png\" width=\"100\" height=\"100\" />\r\n");
      out.write("                  </div>\r\n");
      out.write("                   <div class=\"olapapu\">\r\n");
      out.write("                   <svg xmlns=\"http://www.w3.org/2000/svg\" version=\"1.1\">\r\n");
      out.write("  <defs>\r\n");
      out.write("    <filter id=\"goo\">\r\n");
      out.write("      <feGaussianBlur in=\"SourceGraphic\" result=\"blur\" stdDeviation=\"10\"></feGaussianBlur>\r\n");
      out.write("      <feColorMatrix in=\"blur\" mode=\"matrix\" values=\"1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 21 -7\" result=\"goo\"></feColorMatrix>\r\n");
      out.write("      <feBlend in2=\"goo\" in=\"SourceGraphic\" result=\"mix\"></feBlend>\r\n");
      out.write("    </filter>\r\n");
      out.write("  </defs>\r\n");
      out.write("</svg></div>\r\n");
      out.write("<div class=\"modal-header text-center\">\r\n");
      out.write("<div class=\"buttons\">\r\n");
      out.write("<ul class=\"nav nav-pills\">\r\n");
      out.write("\r\n");
      out.write("                           <li class=\"ButtonFormSession\">\r\n");
      out.write("\r\n");
      out.write("  <button class=\"blob-btn\" id=\"InicioSesionForm\">\r\n");
      out.write("Inicio    <span class=\"blob-btn__inner\">\r\n");
      out.write("      <span class=\"blob-btn__blobs\">\r\n");
      out.write("        <span class=\"blob-btn__blob\"></span>\r\n");
      out.write("        <span class=\"blob-btn__blob\"></span>\r\n");
      out.write("        <span class=\"blob-btn__blob\"></span>\r\n");
      out.write("        <span class=\"blob-btn__blob\"></span>\r\n");
      out.write("      </span>\r\n");
      out.write("    </span></button></li>\r\n");
      out.write("  \r\n");
      out.write("    <li class=\"ButtonFormSession\">\r\n");
      out.write("  <button class=\"blob-btn\" id=\"RegistroForm\">\r\n");
      out.write("Registro\r\n");
      out.write("<span class=\"blob-btn__inner\">\r\n");
      out.write("      <span class=\"blob-btn__blobs\">\r\n");
      out.write("        <span class=\"blob-btn__blob\"></span>\r\n");
      out.write("        <span class=\"blob-btn__blob\"></span>\r\n");
      out.write("        <span class=\"blob-btn__blob\"></span>\r\n");
      out.write("        <span class=\"blob-btn__blob\"></span>\r\n");
      out.write("      </span>\r\n");
      out.write("    </span>\r\n");
      out.write("  </button></li></ul>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("                  <div class=\"modal-body\">\r\n");
      out.write("                     <div class=\"tab-content\" id=\"pills-tabContent\">\r\n");
      out.write("                        <!-- Iniciar Session -->\r\n");
      out.write("                        <div\r\n");
      out.write("                           class=\"tab-pane fade show active\"\r\n");
      out.write("                           id=\"pills-iniciar\"\r\n");
      out.write("                           role=\"tabpanel\">\r\n");
      out.write("                           <form action=\"Controlador\">\r\n");
      out.write("                              <div class=\"form-group\">\r\n");
      out.write("                                 <label>Email address</label>\r\n");
      out.write("                                 <input\r\n");
      out.write("                                    type=\"email\"\r\n");
      out.write("                                    name=\"txtemail\"\r\n");
      out.write("                                    class=\"form-control\"\r\n");
      out.write("                                    placeholder=\"email@example.com\" />\r\n");
      out.write("                              </div>\r\n");
      out.write("                              <div class=\"form-group\">\r\n");
      out.write("                                 <label>Password</label>\r\n");
      out.write("                                 <input\r\n");
      out.write("                                    type=\"password\"\r\n");
      out.write("                                    name=\"txtpass\"\r\n");
      out.write("                                    class=\"form-control\"\r\n");
      out.write("                                    placeholder=\"Password\" />\r\n");
      out.write("                              </div>\r\n");
      out.write("                              <div class=\"ola\"><button\r\n");
      out.write("                                 type=\"submit\"\r\n");
      out.write("                                 name=\"accion\"\r\n");
      out.write("                                 value=\"Validar\"\r\n");
      out.write("                                 class=\"btn btn-outline-danger btn-block\">\r\n");
      out.write("                              Iniciar\r\n");
      out.write("                              </button></div>\r\n");
      out.write("                           </form>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- Registrarse -->\r\n");
      out.write("                        <div\r\n");
      out.write("                           class=\"tab-pane fade\"\r\n");
      out.write("                           id=\"pills-registrar\"\r\n");
      out.write("                           role=\"tabpanel\">\r\n");
      out.write("                           <form action=\"Controlador\">\r\n");
      out.write("                              <div class=\"form-group\">\r\n");
      out.write("                                 <label>Nombres</label>\r\n");
      out.write("                                 <input\r\n");
      out.write("                                    type=\"text\"\r\n");
      out.write("                                    name=\"txtnom\"\r\n");
      out.write("                                    class=\"form-control\"\r\n");
      out.write("                                    placeholder=\"Nombre Apellido Paterno Apellido Materno\" />\r\n");
      out.write("                              </div>\r\n");
      out.write("                              <div class=\"form-group\">\r\n");
      out.write("                                 <label>Boleta</label>\r\n");
      out.write("                                 <input\r\n");
      out.write("                                    type=\"text\"\r\n");
      out.write("                                    maxlength=\"10\"\r\n");
      out.write("                                    name=\"txtboleta\"\r\n");
      out.write("                                    class=\"form-control\"\r\n");
      out.write("                                    placeholder=\"2023090001\" />\r\n");
      out.write("                              </div>\r\n");
      out.write("                              <div class=\"form-group\">\r\n");
      out.write("                                 <label>Grupo</label>\r\n");
      out.write("                                 <input\r\n");
      out.write("                                    type=\"text\"\r\n");
      out.write("                                    name=\"txtdire\"\r\n");
      out.write("                                    class=\"form-control\"\r\n");
      out.write("                                    placeholder=\"4IV9\" />\r\n");
      out.write("                              </div>\r\n");
      out.write("                              <div class=\"form-group\">\r\n");
      out.write("                                 <label>Correo Electrónico</label>\r\n");
      out.write("                                 <input\r\n");
      out.write("                                    type=\"email\"\r\n");
      out.write("                                    name=\"txtemail\"\r\n");
      out.write("                                    class=\"form-control\"\r\n");
      out.write("                                    placeholder=\"correoejemplo@gmail.com\" />\r\n");
      out.write("                              </div>\r\n");
      out.write("                              <div class=\"form-group\">\r\n");
      out.write("                                 <label>Contraseña</label>\r\n");
      out.write("                                 <input\r\n");
      out.write("                                    type=\"password\"\r\n");
      out.write("                                    name=\"txtpass\"\r\n");
      out.write("                                    class=\"form-control\"\r\n");
      out.write("                                    placeholder=\"n0m3l0\" />\r\n");
      out.write("                              </div><div class=\"ola\">\r\n");
      out.write("                              <button\r\n");
      out.write("                                 type=\"submit\"\r\n");
      out.write("                                 name=\"accion\"\r\n");
      out.write("                                 value=\"Registrar\"\r\n");
      out.write("                                 class=\"btn btn-outline-danger btn-block\">\r\n");
      out.write("                              Crear Cuenta\r\n");
      out.write("                              </button></div>\r\n");
      out.write("                           </form>\r\n");
      out.write("                        </div>\r\n");
      out.write("                     </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("      <script>\r\n");
      out.write("              \r\n");
      out.write("$('.buy').click(function(){\r\n");
      out.write("  $(this).closest('.bottom').addClass(\"clicked\");\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("$('.remove').click(function(){\r\n");
      out.write("  $(this).closest('.bottom').removeClass(\"clicked\");\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    var imagenes = [];\r\n");
      out.write("    for (var i = 1; i <= 60; i++) {\r\n");
      out.write("        var rutaImagen = \"SOFTUX/IMAGENES/image\" + i + \".jpg\";\r\n");
      out.write("        imagenes.push(rutaImagen);\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    var indice = 0;\r\n");
      out.write("    \r\n");
      out.write("    setInterval(function() {\r\n");
      out.write("        var loginImg = document.getElementById(\"modalimage\");\r\n");
      out.write("        loginImg.src = imagenes[indice];\r\n");
      out.write("        indice++;\r\n");
      out.write("        if (indice == imagenes.length) {\r\n");
      out.write("            indice = 0;\r\n");
      out.write("        }\r\n");
      out.write("    }, 3000);\r\n");
      out.write("</script>\r\n");
      out.write("      <script>        \r\n");
      out.write("         document.addEventListener(\"DOMContentLoaded\", function() {\r\n");
      out.write("             // Deshabilitar los formularios al cargar la página\r\n");
      out.write("             document.querySelector(\"#pills-iniciar form\").style.display = \"block\";\r\n");
      out.write("             document.querySelector(\"#pills-registrar form\").style.display = \"none\";\r\n");
      out.write("             \r\n");
      out.write("             const OpcionIniciarSesionForm = document.getElementById('InicioSesionForm');\r\n");
      out.write("             const OpcionRegistrarseForm = document.getElementById('RegistroForm');\r\n");
      out.write("             \r\n");
      out.write("         OpcionIniciarSesionForm.addEventListener('click', () => {\r\n");
      out.write("          document.querySelector(\"#pills-iniciar form\").style.display = \"block\";\r\n");
      out.write("             document.querySelector(\"#pills-registrar form\").style.display = \"none\";\r\n");
      out.write("         });\r\n");
      out.write("         \r\n");
      out.write("         OpcionRegistrarseForm.addEventListener('click', () => {\r\n");
      out.write("          document.querySelector(\"#pills-iniciar form\").style.display = \"none\";\r\n");
      out.write("             document.querySelector(\"#pills-registrar form\").style.display = \"block\";\r\n");
      out.write("         });\r\n");
      out.write("         \r\n");
      out.write("         });\r\n");
      out.write("         \r\n");
      out.write("      </script>\r\n");
      out.write("      <script>\r\n");
      out.write("         document.addEventListener('DOMContentLoaded', function() {\r\n");
      out.write("             // Obtener el elemento modal\r\n");
      out.write("             var modal = document.getElementById('myModal');\r\n");
      out.write("         \r\n");
      out.write("             // Deshabilitar la visibilidad del modal al cargar la página\r\n");
      out.write("             modal.style.display = 'none';\r\n");
      out.write("         });\r\n");
      out.write("         \r\n");
      out.write("         \r\n");
      out.write("         document.addEventListener('DOMContentLoaded', function() {\r\n");
      out.write("             // Obtener el botón de cerrar del modal\r\n");
      out.write("             var closeButton = document.querySelector('.close[data-dismiss=\"modal\"]');\r\n");
      out.write("             \r\n");
      out.write("             // Obtener el elemento modal\r\n");
      out.write("             var modal = document.getElementById('myModal');\r\n");
      out.write("         \r\n");
      out.write("             // Agregar evento de click al botón de cerrar\r\n");
      out.write("             closeButton.addEventListener('click', function() {\r\n");
      out.write("                 // Ocultar el modal\r\n");
      out.write("                 modal.style.display = 'none';\r\n");
      out.write("             });\r\n");
      out.write("         });\r\n");
      out.write("         \r\n");
      out.write("      </script>\r\n");
      out.write("      <script>\r\n");
      out.write("         // Captura el elemento que activa el mini menú\r\n");
      out.write("         var dropdownToggle = document.querySelector('.dropdown-toggle');\r\n");
      out.write("         \r\n");
      out.write("         // Captura el mini menú\r\n");
      out.write("         var dropdownMenu = document.querySelector('.dropdown-menu');\r\n");
      out.write("         \r\n");
      out.write("         // Variable para controlar el estado del mini menú\r\n");
      out.write("         var isDropdownVisible = false;\r\n");
      out.write("         \r\n");
      out.write("         // Función para mostrar el mini menú temporalmente al pasar el cursor\r\n");
      out.write("         function showDropdownMenuTemporarily() {\r\n");
      out.write("             dropdownMenu.style.display = 'block';\r\n");
      out.write("             setTimeout(function() {\r\n");
      out.write("                 if (!isDropdownVisible) {\r\n");
      out.write("                     dropdownMenu.style.display = 'none';\r\n");
      out.write("                 }\r\n");
      out.write("             }, 2000); // Duración en milisegundos antes de ocultar el mini menú\r\n");
      out.write("         }\r\n");
      out.write("         \r\n");
      out.write("         // Función para mostrar u ocultar el mini menú\r\n");
      out.write("         function toggleDropdownMenu() {\r\n");
      out.write("             isDropdownVisible = !isDropdownVisible;\r\n");
      out.write("             dropdownMenu.style.display = isDropdownVisible ? 'block' : 'none';\r\n");
      out.write("         }\r\n");
      out.write("         \r\n");
      out.write("         // Agrega un evento para mostrar el mini menú temporalmente al pasar el cursor sobre el elemento\r\n");
      out.write("         dropdownToggle.addEventListener('mouseenter', function(event) {\r\n");
      out.write("             showDropdownMenuTemporarily();\r\n");
      out.write("         });\r\n");
      out.write("         \r\n");
      out.write("         // Agrega un evento para mantener visible el mini menú al presionarlo\r\n");
      out.write("         dropdownToggle.addEventListener('click', function(event) {\r\n");
      out.write("             event.preventDefault(); // Evita que el enlace se ejecute\r\n");
      out.write("             toggleDropdownMenu();\r\n");
      out.write("         });\r\n");
      out.write("         \r\n");
      out.write("         // Agrega un evento para ocultar el mini menú al hacer clic fuera del mini menú o del elemento que lo activa\r\n");
      out.write("         document.addEventListener('click', function(event) {\r\n");
      out.write("             var isClickInside = dropdownToggle.contains(event.target) || dropdownMenu.contains(event.target);\r\n");
      out.write("             if (!isClickInside && isDropdownVisible) {\r\n");
      out.write("                 toggleDropdownMenu();\r\n");
      out.write("             }\r\n");
      out.write("         });\r\n");
      out.write("         \r\n");
      out.write("            \r\n");
      out.write("      </script>\r\n");
      out.write("      <script>\r\n");
      out.write("         // Captura el elemento que activa el modal\r\n");
      out.write("         var modalToggle = document.querySelector('[data-toggle=\"modal\"][data-target=\"#myModal\"]');\r\n");
      out.write("         \r\n");
      out.write("         // Captura el modal\r\n");
      out.write("         var modal = document.getElementById('myModal');\r\n");
      out.write("         \r\n");
      out.write("         // Variable para controlar el estado del modal\r\n");
      out.write("         var isModalVisible = false;\r\n");
      out.write("         // Función para mostrar u ocultar el modal\r\n");
      out.write("         function toggleModal() {\r\n");
      out.write("             isModalVisible = !isModalVisible;\r\n");
      out.write("             modal.style.display = isModalVisible ? 'block' : 'none';\r\n");
      out.write("         }\r\n");
      out.write("         \r\n");
      out.write("         \r\n");
      out.write("         // Agrega un evento para mostrar el modal temporalmente al pasar el cursor sobre el elemento\r\n");
      out.write("         modalToggle.addEventListener('mouseenter', function(event) {\r\n");
      out.write("             showModalTemporarily();\r\n");
      out.write("         });\r\n");
      out.write("         \r\n");
      out.write("         // Agrega un evento para mantener visible el modal al presionarlo\r\n");
      out.write("         modalToggle.addEventListener('click', function(event) {\r\n");
      out.write("             event.preventDefault(); // Evita que el enlace se ejecute\r\n");
      out.write("             toggleModal();\r\n");
      out.write("             isDropdownVisible = !isDropdownVisible;\r\n");
      out.write("             dropdownMenu.style.display = isDropdownVisible ? 'block' : 'none';\r\n");
      out.write("         });\r\n");
      out.write("         \r\n");
      out.write("         // Agrega un evento para ocultar el modal al hacer clic fuera del modal o del elemento que lo activa\r\n");
      out.write("         document.addEventListener('click', function(event) {\r\n");
      out.write("             var isClickInside = modalToggle.contains(event.target) || modal.contains(event.target);\r\n");
      out.write("             if (!isClickInside && isModalVisible) {\r\n");
      out.write("                 toggleModal();\r\n");
      out.write("             }\r\n");
      out.write("         });\r\n");
      out.write("         \r\n");
      out.write("      </script>\r\n");
      out.write("      <script src=\"js/index.js\" type=\"text/javascript\"></script>\r\n");
      out.write("   </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /index.jsp(97,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${correo == 'empresa@gmail.com' or correo == 'otroemail@gmail.com' or correo == 'terceremail@gmail.com'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("  <input type=\"text\" id=\"searchInput\" placeholder=\"Buscar...\" onkeyup=\"searchProducts()\">\r\n");
          out.write("  <!-- Campo de selección de fecha -->\r\n");
          out.write("  <input type=\"date\" id=\"searchDate\" onchange=\"searchProducts()\" style=\"display:none;\"> <!-- Nuevo campo de fecha, inicialmente oculto -->\r\n");
          out.write("  <!-- Botón de selección -->\r\n");
          out.write("  <select id=\"searchOption\" onchange=\"toggleSearchFields()\">\r\n");
          out.write("      <option value=\"name\">Buscar por nombre</option>\r\n");
          out.write("      <option value=\"description\">Buscar por descripción</option>\r\n");
          out.write("      <option value=\"date\">Buscar por fecha</option> <!-- Nueva opción de búsqueda por fecha -->\r\n");
          out.write("  </select>\r\n");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /index.jsp(158,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${correo == 'empresa@gmail.com'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("  ");
          if (_jspx_meth_c_005fforEach_005f0(_jspx_th_c_005fif_005f1, _jspx_page_context))
            return true;
          out.write('\r');
          out.write('\n');
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /index.jsp(159,2) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/index.jsp(159,2) '${reportes}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${reportes}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /index.jsp(159,2) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("p");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("    <div class=\"wrapper\" data-product-name=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.getNombres()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" data-product-description=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.getDescripcion()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" data-product-date=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.getFechasuceso()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("      <div class=\"container\">\r\n");
            out.write("        <div class=\"top\"></div>\r\n");
            out.write("        <div class=\"bottom\">\r\n");
            out.write("          <div class=\"left\">\r\n");
            out.write("            <div class=\"details\">\r\n");
            out.write("              <h1>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.getNombres()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</h1>\r\n");
            out.write("              <p>£250</p>\r\n");
            out.write("            </div>\r\n");
            out.write("            <a href=\"Controlador?accion=AgregarCarrito&id=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.getId()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" class=\"btn btn2 btn-outline-primary\">\r\n");
            out.write("              <div class=\"buy\"><i class=\"material-icons\">add_shopping_cart</i></div>\r\n");
            out.write("            </a>\r\n");
            out.write("          </div>\r\n");
            out.write("          <div class=\"right\">\r\n");
            out.write("            <div class=\"done\"><i class=\"material-icons\">done</i></div>\r\n");
            out.write("            <div class=\"details\">\r\n");
            out.write("              <h1>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.getNombres()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</h1>\r\n");
            out.write("              <p>Listo para revisión</p>\r\n");
            out.write("            </div>\r\n");
            out.write("            <div class=\"remove\"><i class=\"material-icons\">clear</i></div>\r\n");
            out.write("          </div>\r\n");
            out.write("        </div>\r\n");
            out.write("      </div>\r\n");
            out.write("      <div class=\"inside\">\r\n");
            out.write("        <div class=\"icon\"><i class=\"material-icons\">info_outline</i></div>\r\n");
            out.write("        <div class=\"contents\">\r\n");
            out.write("          <table>\r\n");
            out.write("            <tr>\r\n");
            out.write("              <th>Descripción</th>\r\n");
            out.write("              <th>Fecha</th>\r\n");
            out.write("            </tr>\r\n");
            out.write("            <tr>\r\n");
            out.write("              <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.getDescripcion()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("              <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.getFechasuceso()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("            </tr>\r\n");
            out.write("          </table>\r\n");
            out.write("        </div>\r\n");
            out.write("      </div>\r\n");
            out.write("    </div>\r\n");
            out.write("  ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
